### PR TITLE
Docs/acc testing

### PR DESCRIPTION
**Pull request by jagosherred**
#135 
Struggling with this section - let me know if anyone has any thoughts to add.

### CODE REVIEW

**Comment by joekendal** [comment]
Idk either tbh (they don't teach this stuff on Udemy 😅)

I would add that the 3rd paragraph comes across as an honest way to answer the section, however we have applied more of it than you think. 

For example, in terms of questionnaires, I believe we exchanged a number of emails with the client that contained numbered bullet points of questions and answers. A lot was understood through email interaction than through video calls that sometimes led to confusion and miscommunication.

Another thing is that we exchanged demos, Q & As and other communication with Data Sim team which ultimately led to accommodating their needs (although not sure if that counts as acceptance testing since they are not the client)

**Review by joekendal — COMMENTED** [review]
Those are just my initial thoughts. I'll have a look later.

**Comment by armandcismaru** [comment]
Yeah pretty tough section, I will look at it and try to help. Most probably tomorrow as I had a 6 hours long workshop for HCI, my brain it's fried 🤣

**Review by armandcismaru — COMMENTED** [review]
Good start, we'll complete and polish it

**Comment by jagosherred** [comment]
Okay cheers guys - will have a go tomorrow morn writing up a draft with what you've mentioned

**Comment by jagosherred** [comment]
made a couple of additions which hopefully covers joes points but still not 100% about it

**Review by joekendal — COMMENTED** [review]
Seems okay may be a bit verbose

**Review by armandcismaru — COMMENTED** [review]
I think we could also add the fact that we gave access to our lake to the Analytics team 
Also I think we could explain how we evaluated independently that our infrastructure spins up and does what it needs to do by manually uploading data and doing queries

**Comment by armandcismaru** [comment]
yeah we could brush up the phrases a bit

**Comment by jagosherred** [comment]
Read through and made a couple changes but dont know to make more any concise without losing points - if others want to have a go then please go ahead. This section is up to 2 pages though and thats less then a page so far so might just be fine.

**Review by joekendal — APPROVED** [review]

**Pull request merged**
